---
- name: Install Harbor
  include: install.yml
  tags: install

- name: Manage users
  include: users_management.yml
  tags: users

- name: Install aquasec trivy
  include: aquasec_trivy.yml
  tags: aquasec_trivy

- name: Add Docker Hub replicaiton
  include: replication_dockerhub.yml
  tags: replication_dockerhub
